---
processor:
  graphite:
    host: 127.0.0.1
    port: 2003
  supported:
    # list of countries supported by the consumer
    countries: IE, IT, UK, DE, US, FR, ES, JP
    # list of currencies supported by the consumer
    currencies: EUR, USD, GBP, JPY
